version: "3.6"


services:
  app:
    image: spring-boot
    build:
      context: .
      target: ${APP_ENV}
    ports:
      - "8080:8080"
    volumes:
      - .:/app


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_2
    ports:
      - '8082:80'
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
    depends_on:
      - db


  db:
    image: mysql:8.0
    container_name: mysql_2
    ports:
      - '3306:3306'
    restart: always
    environment:
      MYSQL_DATABASE: skell
      MYSQL_USER: me
      MYSQL_PASSWORD: 12345678
      MYSQL_ROOT_PASSWORD: 12345678
    volumes:
      - db-data:/var/lib/mysql
      - /etc/localtime:/etc/localtime

volumes:
  db-data: {}